<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

class openluckRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            "confirm_code"=>["required"]
        ];
    }
    protected function failedValidation(Validator $validator)
    {
        session()->flash("validationerror",true);
//        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
}
